services:
  spacerework:
    env_file: ../../.env
    platform: linux/amd64
    image: ${APP_NAME}-app-image
    container_name: ${APP_NAME}-app-container
    hostname: ${APP_NAME}-app-container
    build:
      context: ../../
      dockerfile: ./docker/app/Dockerfile
      args:
        RUST_VERSION: 1.85
        BASE_OS: slim
    ports:
      - '3000:3000'
    volumes:
      - ../..:/app
    tty: true
    command: ["docker/app/post_build.sh"]
    networks:
      - default

networks:
  default:
    external: true
    name: ${APP_NAME}-docker-network